version: "3.9"

services: 
  mongo:
    image: mongo:latest
    container_name: containerMongo
    ports:
      - 27017:27017
    volumes: 
      - data:/data/db
      - ./dump:/dump
    restart: always
    env_file: 
      - env

  paytest:
    build: .
    container_name: containerPayTest
    ports: 
      - 3000:3000
    depends_on: 
      - mongo
    links: 
      - mongo
    env_file: 
      - env

volumes: 
  data: 